language: r
cache: packages

r:
#  - oldrel
  - release
  - devel

r_packages:
  - covr

addons:
  apt:
    packages:
      - libgsl0-dev # For RCppZigg

## Only run covr on release
after_success:
  - Rscript -e "if(length(grep('2\$', ${TRAVIS_JOB_NUMBER}))) covr::codecov()";

notifications:
  email:
    on_success: change
    on_failure: change

