language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh run_script -e 'install.packages("benchmarkme", repos=c("https://cran.rstudio.com/","http://csgillespie.github.io/drat/"))'
  - ./pkg-build.sh install_r covr
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_success:
   - if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov()'; fi
  
after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=devel
    - RVERSION=release  COVERAGE=true
    - RVERSION=oldrel
